import type { NextPage } from "next";
import Head from "next/head";
import Header  from '../components/layout/Header';


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>IngoBook - Main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header />
      <main>

      </main>

      <footer>
      </footer>
      </>
  );
};

export default Home;
